//! Tokens built into the SQL language.

use lib_parse::{common::token::*, define_tokens};

define_tokens! {
    Ident [is_keyword] {
        [abort]             Abort
        [action]            Action
        [add]               Add
        [after]             After
        [all]               All
        [alter]             Alter
        [always]            Always
        [analyze]           Analyze
        [and]               And
        [as]                As
        [asc]               Asc
        [attach]            Attach
        [autoincrement]     Autoincrement
        [before]            Before
        [begin]             Begin
        [between]           Between
        [by]                By
        [cascade]           Cascade
        [case]              Case
        [cast]              Cast
        [check]             Check
        [collate]           Collate
        [column]            Column
        [commit]            Commit
        [conflict]          Conflict
        [constraint]        Constraint
        [create]            Create
        [cross]             Cross
        [current]           Current
        [current_date]      CurrentDate
        [current_time]      CurrentTime
        [current_timestamp] CurrentTimestamp
        [database]          Database
        [default]           Default
        [deferrable]        Deferrable
        [deferred]          Deferred
        [delete]            Delete
        [desc]              Desc
        [detach]            Detach
        [distinct]          Distinct
        [do]                Do
        [drop]              Drop
        [each]              Each
        [else]              Else
        [end]               End
        [escape]            Escape
        [except]            Except
        [exclude]           Exclude
        [exclusive]         Exclusive
        [exists]            Exists
        [explain]           Explain
        [fail]              Fail
        [filter]            Filter
        [first]             First
        [following]         Following
        [for]               For
        [foreign]           Foreign
        [from]              From
        [full]              Full
        [generated]         Generated
        [glob]              Glob
        [group]             Group
        [groups]            Groups
        [having]            Having
        [if]                If
        [ignore]            Ignore
        [immediate]         Immediate
        [in]                In
        [index]             Index
        [indexed]           Indexed
        [initially]         Initially
        [inner]             Inner
        [insert]            Insert
        [instead]           Instead
        [intersect]         Intersect
        [into]              Into
        [is]                Is
        [isnull]            Isnull
        [join]              Join
        [key]               Key
        [last]              Last
        [left]              Left
        [like]              Like
        [limit]             Limit
        [match]             Match
        [materialized]      Materialized
        [natural]           Natural
        [no]                No
        [not]               Not
        [nothing]           Nothing
        [notnull]           Notnull
        [null]              Null
        [nulls]             Nulls
        [of]                Of
        [offset]            Offset
        [on]                On
        [or]                Or
        [order]             Order
        [others]            Others
        [outer]             Outer
        [over]              Over
        [partition]         Partition
        [plan]              Plan
        [pragma]            Pragma
        [preceding]         Preceding
        [primary]           Primary
        [query]             Query
        [raise]             Raise
        [range]             Range
        [recursive]         Recursive
        [references]        References
        [regexp]            Regexp
        [reindex]           Reindex
        [release]           Release
        [rename]            Rename
        [replace]           Replace
        [restrict]          Restrict
        [returning]         Returning
        [right]             Right
        [rollback]          Rollback
        [row]               Row
        [rows]              Rows
        [savepoint]         Savepoint
        [select]            Select
        [set]               Set
        [table]             Table
        [temp]              Temp
        [temporary]         Temporary
        [then]              Then
        [ties]              Ties
        [to]                To
        [transaction]       Transaction
        [trigger]           Trigger
        [unbounded]         Unbounded
        [union]             Union
        [unique]            Unique
        [update]            Update
        [using]             Using
        [vacuum]            Vacuum
        [values]            Values
        [view]              View
        [virtual]           Virtual
        [when]              When
        [where]             Where
        [window]            Window
        [with]              With
        [without]           Without
    }

    Punct {
        [*] Asterisk
        [,] Comma
        [;] Semicolon
    }
}
